"""Adding new car table

Revision ID: 2856ecc6c25f
Revises: 38aac8f310dd
Create Date: 2021-04-30 10:21:50.634069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2856ecc6c25f'
down_revision = '38aac8f310dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drone',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('camera_quality', sa.String(length=150), nullable=True),
    sa.Column('flight_time', sa.String(length=100), nullable=True),
    sa.Column('max_speed', sa.String(length=100), nullable=True),
    sa.Column('dimensions', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.String(length=50), nullable=True),
    sa.Column('cost_of_prd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('series', sa.String(length=150), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('seat')
    op.drop_table('concession')
    op.drop_table('ticket')
    op.drop_table('brand')
    op.drop_table('movie')
    op.drop_table('customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('customer_id', sa.INTEGER(), server_default=sa.text("nextval('customer_customer_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('billing_info', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('customer_id', name='customer_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('movie',
    sa.Column('movie_id', sa.INTEGER(), server_default=sa.text("nextval('movie_movie_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('movie_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], name='movie_customer_id_fkey'),
    sa.PrimaryKeyConstraint('movie_id', name='movie_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('brand',
    sa.Column('seller_id', sa.INTEGER(), server_default=sa.text("nextval('brand_seller_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('brand_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('contact_number', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('seller_id', name='brand_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('ticket',
    sa.Column('ticket_id', sa.INTEGER(), server_default=sa.text("nextval('ticket_ticket_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('order_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=True),
    sa.Column('sub_total', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.movie_id'], name='ticket_movie_id_fkey'),
    sa.PrimaryKeyConstraint('ticket_id', name='ticket_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('concession',
    sa.Column('item_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('prod_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], name='concession_customer_id_fkey'),
    sa.ForeignKeyConstraint(['seller_id'], ['brand.seller_id'], name='concession_seller_id_fkey'),
    sa.PrimaryKeyConstraint('item_id', name='concession_pkey')
    )
    op.create_table('seat',
    sa.Column('seat_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('movie_name', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ticket_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.ticket_id'], name='seat_ticket_id_fkey'),
    sa.PrimaryKeyConstraint('seat_id', name='seat_pkey')
    )
    op.drop_table('drone')
    # ### end Alembic commands ###
