"""Initial migration.

Revision ID: d6bb92c1bb4a
Revises: 2856ecc6c25f
Create Date: 2021-04-30 13:38:15.633220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6bb92c1bb4a'
down_revision = '2856ecc6c25f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drone', sa.Column('fuel_capacity', sa.String(length=100), nullable=True))
    op.add_column('drone', sa.Column('miles', sa.Numeric(precision=150), nullable=True))
    op.drop_column('drone', 'camera_quality')
    op.drop_column('drone', 'flight_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drone', sa.Column('flight_time', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('drone', sa.Column('camera_quality', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('drone', 'miles')
    op.drop_column('drone', 'fuel_capacity')
    # ### end Alembic commands ###
